# permissions for end users to view randoms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crd-operator
    app.kubernetes.io/managed-by: kustomize
  name: random-viewer-role
rules:
- apiGroups:
  - random.example.com
  resources:
  - randoms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - random.example.com
  resources:
  - randoms/status
  verbs:
  - get
